using System;
namespace HashTable
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("****Welcome to Hash Table****");
            //UC1:-Ability to find Frequency of words in a sentence 
            MyMapNode<string, string> node = new MyMapNode<string, string>(5);
            node.Add("0", "To");
            node.Add("1", "Be");
            node.Add("2", "Or");
            node.Add("3", "Not");
            node.Add("4", "To");
            node.Add("5", "Be");
            string node0 = node.Get("0");
            Console.WriteLine("1st index value: " + node0);
            string node1 = node.Get("1");
            Console.WriteLine("2nd index value: " +node1);
            Console.WriteLine("3rd index value: "+node.Get("2"));
            //UC2:-Ability to find Frequency of word in a large Paragraph phrase
            Console.WriteLine("============================");
            string paragraph = "Paranoids are not paranoid because they are paranoid but because they keep putting themselves deliberately into paranoid avoidable situations";
            ///Split method returns an array of strings generated by splitting of original string.
            string[] para = paragraph.Split(" ");
            ///Creating reference of MyMapNode.
            MyMapNode<int, string> nodeone = new MyMapNode<int, string>(para.Length);
            int key = 0;
            ///foreach iterates on paragraph and adds key and value to hash.
            foreach (string word in para)
            {
                nodeone.Add(key, word);
                key++;
            }
            Console.WriteLine("Frequency :" + nodeone.GetFrequency("avoidable"));
            //UC3:-
            nodeone.RemoveValue("avoidable");
            Console.WriteLine("Frequency :" + nodeone.GetFrequency("avoidable"));
        }
    }
}
